# Changes here will be overwritten by Copier
_commit: 0.1.3
_src_path: gh:stkr22/copier-python-project
author_email: stkr22@github.com
author_full_name: stkr22
copyright_license: GNU General Public License v3.0
project_description: Comms Bridge is an open-source endpoint designed to facilitate
    speech interaction within smart assistant systems, optimized for operation on
    edge devices.
project_name: Private Assistant Comms Bridge
python_package_distribution_name: private-assistant-comms-bridge
python_package_import_name: private_assistant_comms_bridge
version: 0.1.0
