[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "private-assistant-comms-bridge"
version = "1.3.0"
description = "Comms Bridge is an open-source endpoint designed to facilitate speech interaction within smart assistant systems, optimized for operation on edge devices."
authors = ["stkr22 <stkr22@github.com>"]
readme = "README.md"
license = "GNU General Public License v3.0"

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
httpx = "^0.27.0"
pyyaml = "^6.0.1"
pydantic = "^2.7.3"
private-assistant-commons = "^1.1.2"
fastapi = "^0.111.0"
speexdsp-ns = "^0.1.2"
numpy = "1.26.4"
aiomqtt = "^2.3.0"
openwakeword = {git = "https://github.com/stkr22/openWakeWord.git", rev = "af84a81"}
onnxruntime = "^1.20.0"
pysilero-vad = "^2.0.0"

[tool.poetry.group.dev.dependencies]
ruff = "^0.7.1"
mypy = "^1.13.0"
pytest = "^8.3.3"
types-pyyaml = "^6.0.12.20240311"

[[tool.mypy.overrides]]
module = [
    "openwakeword.*",
    "pyaudio.*"
]
ignore_missing_imports = true

[tool.ruff]
target-version = "py312"
line-length = 120
indent-width = 4

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I", "UP"]
ignore = ["E203"]
