[tool.poetry]
name = "private-assistant-comms-bridge"
version = "1.0.10"
description = "Comms Bridge is an open-source endpoint designed to facilitate speech interaction within smart assistant systems, optimized for operation on edge devices."
authors = ["stkr22 <stkr22@github.com>"]
readme = "README.md"
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
librosa = "^0.10.2.post1"
paho-mqtt = "^2.1.0"
openwakeword = "^0.6.0"
httpx = "^0.27.0"
pyyaml = "^6.0.1"
pydantic = "^2.7.3"
typer = {extras = ["all"], version = "^0.12.3"}
torchaudio = "^2.3.1"
private-assistant-commons = "^0.1.0"
websockets = "^12.0"
aiortc = "^1.9.0"
aiohttp = "^3.9.5"
fastapi = "^0.111.0"
speexdsp-ns = "^0.1.2"
numpy = "1.26.4"

[tool.poetry.group.dev.dependencies]
ruff = "^0.4.8"
mypy = "^1.10.0"
pytest = "^8.2.2"
types-pyyaml = "^6.0.12.20240311"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
target-version = "py311"
line-length = 88
indent-width = 4

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I", "UP"]
ignore = ["E203"]
