FROM mcr.microsoft.com/devcontainers/base@sha256:da67c59f82e057e0ccb81ec7d13fb50464c26f477638018e6de1b2623a008a3a
COPY --from=ghcr.io/astral-sh/uv:0.5.14@sha256:f0786ad49e2e684c18d38697facb229f538a6f5e374c56f54125aabe7d14b3f7 /uv /uvx /bin/
ENV VIRTUAL_ENV=/workspaces/.venv
ENV UV_PROJECT_ENVIRONMENT=/workspaces/.venv
RUN mkdir -p /workspaces && \
    chown -R vscode:vscode /workspaces
# additional proejct dependencies
RUN apt-get update && apt-get install -y libspeexdsp-dev git && \
    rm -rf /var/lib/apt/lists/*
USER vscode
